#!/bin/bash

if [ $(id -u) != 0 ] 
then
    exec sudo su -c "$0 $@"
fi

# I am root
apt-get update && apt-get install -y git

config_dir="/etc/com.snwfdhmp.server-install/"
mkdir -p $config_dir
git clone https://github.com/snwfdhmp/server-install.git $config_dir
cd $config_dir
chmod u+x run.sh
./run.sh ${@:-$(cat /dev/stdin)}